services:
  frontend:
    build:
      context: ./glossary-front
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:80"  # Сервинг React через Nginx
    restart: always

  backend:
    build:
      context: ./glossary-back
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8100:8100"
    restart: always
