services:
  frontend:
    build:
      context: ./glossary-front
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:80"  # Сервинг React через Nginx
    restart: always

  backend:
    build:
      context: ./glossary-back
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DATABASE_URL=sqlite:///./database.db  # SQLite
    depends_on:
      - db

  db:
    image: nouchka/sqlite3  # SQLite в контейнере
    container_name: sqlite_service
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
