name: Deploy React and FastAPI

on:
  push:
    branches:
      - main  # Запускается при пуше в ветку main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      # Шаг 3: Устанавливаем зависимости
      - name: Install Backend Dependencies
        run: |
          cd glossary-back
          python -m venv venv
          pip install -r requirements.txt

      # Шаг 4: Запуск FastAPI на GitHub Actions
      - name: Run FastAPI Server
        run: |
          cd glossary-back
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend  # Выполняется после завершения build-backend

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Шаг 3: Устанавливаем зависимости и билдим
      - name: Install and Build Frontend
        run: |
          cd glossary-front
          npm install
          npm run build

      # Шаг 4: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./glossary-front/build
