name: Run Express and React Servers

on:
  push:
    branches:
      - main

jobs:
  run-servers:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # or the version you need

      # Step 3: Install and run Express server
      - name: Install and start Express server
        run: |
          cd glossary-back
          npm install
          nohup npm start &
        env:
          PORT: 8100

      # Step 4: Install and run React app
      - name: Install and start React app
        run: |
          cd glossary-front
          npm install
          nohup npm start &
        env:
          PORT: 3000
